### ISSUE TITLE
Zellij plugin out of scope

### ISSUE THREAD

**Issue by allaboutevemirolive** [merikan/dotfiles#2]
Hi, I'm getting this weird rendering if I create more tabs. By the way, I love this Gruvbox plugin! Thank you for this config file.

![a_zellij_err](https://github.com/user-attachments/assets/addabd44-55b0-48ae-aa39-022bd21ab7a2)

**Comment by allaboutevemirolive** [comment]
Nevermind, I do think this is default behaviour in zellij

**Comment by merikan** [comment]
Hi @allaboutevemirolive Sorry, but I totally missed your message.
To be honest I didn't understand what your problem was but I guess it's ok now?

Glad you liked my themes. I have updated them to make use of color alias and made som small changes to. You can find them here https://github.com/merikan/.dotfiles/tree/main/config/zellij/themes/zjstatus
